[tools]
age = "1.1.1"
checkov = "latest"
flux2 = "latest"
helm = "latest"
k9s = "latest"
pre-commit = "latest"
python = "latest"
sops = "latest"
talhelper = "latest"
talosctl = "latest"
terraform = "latest"
terraform-docs = "latest"
terrascan = "latest"
tflint = "latest"
trivy = "latest"
tfupdate = "latest"
"npm:commitlint" = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"

[tasks.refreshTalosConfig]
description = "Refresh Talos config"
run = "terraform output -json talosconfig | jq -r .talos_config > ~/.talos/config"

[tasks.removeCompletedPods]
run = "kubectl delete pod --field-selector=status.phase==Succeeded --all-namespaces"

description = "Remove completed pods"

[tasks.removeFailedPods]
run = "kubectl delete pod --field-selector=status.phase==Failed --all-namespaces"
description = "Remove failed pods"

[tasks.updateCiliumHelmTemplate]
description = "Update Cilium helm template"
run = """
helm template \
    cilium \
    cilium/cilium \
    --version 1.17.2 \
    --namespace kube-system \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=true \
    --set securityContext.capabilities.ciliumAgent=\"{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}\" \
    --set securityContext.capabilities.cleanCiliumState=\"{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}\" \
    --set cgroup.autoMount.enabled=false \
    --set cgroup.hostRoot=/sys/fs/cgroup \
    --set k8sServiceHost=localhost \
    --set k8sServicePort=7445 \
    --set loadBalancer.acceleration=native \
    --set ingressController.enabled=true \
    --set ingressController.default=true \
    --set ingressController.loadbalancerMode=dedicated \
    --set bpf.lbExternalClusterIP=true \
    --set bgpControlPlane.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set gatewayAPI.enabled=true \
    --set gatewayAPI.enableAlpn=true \
    --set gatewayAPI.enableAppProtocol=true \
    > cilium.yaml
"""

[tasks.upgradeCiliumViaHelm]
description = "Upgrade Cilium via Helm"
run = """
helm upgrade \
  cilium \
  cilium/cilium \
  --version 1.17.2 \
  --namespace kube-system \
  --set ipam.mode=kubernetes \
  --set kubeProxyReplacement=true \
  --set securityContext.capabilities.ciliumAgent=\"{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}\" \
  --set securityContext.capabilities.cleanCiliumState=\"{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}\" \
  --set cgroup.autoMount.enabled=false \
  --set cgroup.hostRoot=/sys/fs/cgroup \
  --set k8sServiceHost=localhost \
  --set k8sServicePort=7445 \
  --set loadBalancer.acceleration=native \
  --set ingressController.enabled=true \
  --set ingressController.default=true \
  --set ingressController.loadbalancerMode=dedicated \
  --set bpf.lbExternalClusterIP=true \
  --set bgpControlPlane.enabled=true \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
    --set gatewayAPI.enabled=true \
    --set gatewayAPI.enableAlpn=true \
    --set gatewayAPI.enableAppProtocol=true \
"""
