[tools]
checkov = "latest"
flux2 = "latest"
helm = "latest"
k9s = "latest"
pre-commit = "latest"
talhelper = "latest"
talosctl = "latest"
terraform = "latest"
terraform-docs = "latest"
terrascan = "latest"
tflint = "latest"
trivy = "latest"
tfupdate = "latest"
"npm:commitlint" = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"

[tasks.updateCiliumHelmTemplate]
description = "Update Cilium helm template"
run = """
helm template \
    cilium \
    cilium/cilium \
    --version 1.15.0 \
    --namespace kube-system \
    --set ipam.mode=kubernetes \
    --set=kubeProxyReplacement=true \
    --set=securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set=securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set=cgroup.autoMount.enabled=false \
    --set=cgroup.hostRoot=/sys/fs/cgroup \
    --set=k8sServiceHost=localhost \
    --set=k8sServicePort=7445 > cilium.yaml
"""
