---
# https://docs.cilium.io/en/stable/helm-reference/

autoDirectNodeRoutes: true

bgpControlPlane:
  enabled: true

bpf:
  lbExternalClusterIP: true

cgroup:
  autoMount:
    enabled: false
  hostRoot: "/sys/fs/cgroup"

directRoutingSkipUnreachable: true

enableIPv4BIGTCP: false
enableIPv6BIGTCP: false

envoy:
  rollOutPods: true

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

hubble:
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: dedicated

ipam:
  mode: kubernetes

ipv4:
  enabled: true

ipv4NativeRoutingCIDR: "10.0.0.8/8"

ipv6:
  enabled: false

ipv6NativeRoutingCIDR: "fd00::/100"

k8sServiceHost: localhost
k8sServicePort: 7445

kubeProxyReplacement: true

loadBalancer:
  acceleration: native

operator:
  rollOutPods: true

rollOutCiliumPods: true

routingMode: native

securityContext:
  capabilities:
    # yamllint disable-line rule:line-length
    ciliumAgent:
      [
        CHOWN,
        KILL,
        NET_ADMIN,
        NET_RAW,
        IPC_LOCK,
        SYS_ADMIN,
        SYS_RESOURCE,
        DAC_OVERRIDE,
        FOWNER,
        SETGID,
        SETUID,
      ]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
